import {
  trackSignup,
  trackUsernameCreated,
  trackLinkAdded,
  trackLinkDeleted,
  trackLinkClicked,
  trackLinksReordered,
  trackThemeChanged,
  trackThemeColorsChanged,
  trackPremiumCTAClicked,
  trackBeginCheckout,
  trackPurchase,
  trackProfileViewed,
  trackCustomDomainSet,
  trackCustomDomainVerified,
  trackCustomDomainRemoved,
  trackLanguageChanged,
  setLanguageProperty,
  setUserTypeProperty,
  setHasBiolinkProperty,
  setLinkCountProperty,
  trackDeleteAccountStarted,
  trackAccountDeleted,
  trackUserLinkClick,
  trackFeedbackSubmitted,
} from '~/lib/analytics-events'

export function useAnalytics() {
  return {
    trackSignup,
    trackUsernameCreated,
    trackLinkAdded,
    trackLinkDeleted,
    trackLinkClicked,
    trackLinksReordered,
    trackThemeChanged,
    trackThemeColorsChanged,
    trackPremiumCTAClicked,
    trackBeginCheckout,
    trackPurchase,
    trackProfileViewed,
    trackCustomDomainSet,
    trackCustomDomainVerified,
    trackCustomDomainRemoved,
    trackLanguageChanged,
    setLanguageProperty,
    setUserTypeProperty,
    setHasBiolinkProperty,
    setLinkCountProperty,
    trackDeleteAccountStarted,
    trackAccountDeleted,
    trackUserLinkClick,
    trackFeedbackSubmitted,
  }
}
